#!/usr/bin/env python3
from sys import argv

from lib.arch_pkg import pacman as pac, yaourt as aur
from lib import xfce, fs, vera

force = "-f" in argv[1:]
vera.merge_to_dir("~/SpiderOak Hive/ssh", "~/.ssh/", force)                             # secrets

xfce.kb_set("/xfwm4/custom/<Control><Alt>Down",  "hide_window_key",     create=True) # wm stuff
xfce.kb_set("/xfwm4/custom/<Control><Alt>Left",  "tile_left_key",       create=True)
xfce.kb_set("/xfwm4/custom/<Control><Alt>Right", "tile_right_key",      create=True)
xfce.kb_set("/xfwm4/custom/<Control><Alt>Up",    "maximize_window_key", create=True)
xfce.kb_unset("/xfwm4/custom/<Alt>F6",     "stick_window_key")  # < conflicts with intellij
xfce.kb_unset("/xfwm4/custom/<Alt>F7",     "move_window_key")   # < conflicts with intellij
xfce.kb_unset("/xfwm4/custom/<Alt>Insert", "add_workspace_key") # < conflicts with intellij
xfce.wm_set("/general/mousewheel_rollup", "false")
xfce.wm_set("/general/scroll_workspaces", "false")

print("You might want to xfwm4 --replace if new shortcuts where set")

print("All good!")
