#!/usr/bin/env python3
from lib.arch_pkg import pacman as pac, yaourt as aur
from lib import xfce, fs

pac("yaourt", "vim")                                                            # basics
aur("google-chrome")                                                            # browsers
pac("firefox")
aur("freetype2-ubuntu", "fontconfig-ubuntu", "cairo-ubuntu")                    # better fonts
pac("redshift")                                                                 # my eyes
aur("caffeine-ng")
aur("prezto-git", "terminator")                                                 # shell
pac("git", "meld", "cloc")                                                      # dev
pac("jdk8-openjdk")
pac("python2-pip", "python2-virtualenv")
pac("python-pip", "python-virtualenv", "python-virtualenvwrapper")
aur("intellij-idea-community-edition", "pycharm-community", "atom-editor-bin")

fs.merge("files/terminator_config", "~/.config/terminator/config", mkdir=True)  # files
fs.merge("files/zshrc", "~/.zshrc")
fs.merge("files/profile", "~/.profile")
fs.merge("files/vimrc", "~/.vimrc")
fs.merge("files/gitconfig", "~/.gitconfig")
fs.merge("files/magnoster.zsh-theme", "~/.bin/magnoster.zsh-theme", mkdir=True)
fs.symlink("~/.bin/magnoster.zsh-theme", "/usr/lib/prezto/modules/prompt/functions/prompt_magnoster_setup", sudo=True)

xfce.kb_set("/xfwm4/custom/<Primary><Alt>Down", "hide_window_key", create=True) # wm stuff
xfce.kb_set("/xfwm4/custom/<Primary><Alt>Left", "tile_left_key", create=True)
xfce.kb_set("/xfwm4/custom/<Primary><Alt>Right", "tile_right_key", create=True)
xfce.kb_set("/xfwm4/custom/<Primary><Alt>Up", "maximize_window_key", create=True)
xfce.kb_unset("/xfwm4/custom/<Alt>F6", "stick_window_key")                      # < messes up intellij, TODO: test kb_unset!
xfce.wm_set("/general/mousewheel_rollup", "false")
xfce.wm_set("/general/scroll_workspaces", "false")

print("All good!")
