#!/usr/bin/env python3
from sys import argv

from lib.arch_pkg import pacman as pac, yaourt as aur
from lib.pip import pip2, pip3
from lib import xfce, fs, vera

force = "-f" in argv[1:]

pac("yaourt", "vim")                                                            # basics
aur("spideroak-one")
aur("google-chrome")                                                            # browsers
pac("firefox")
#aur("freetype2-ubuntu", "fontconfig-ubuntu", "cairo-ubuntu")                    # better fonts
pac("redshift")                                                                 # my eyes
aur("caffeine-ng")
aur("prezto-git", "terminator")                                                 # shell
pac("git", "meld", "cloc")                                                      # dev
pac("tk", "aspell-en")                                                          # gitk
pac("jdk8-openjdk")
pac("python2-pip", "python2-virtualenv")
pac("python-pip", "python-virtualenv", "python-virtualenvwrapper")
aur("fabric")
aur("intellij-idea-community-edition", "pycharm-community", "atom-editor-bin")
pac("docker", "docker-compose")                                                 # docker
aur("haroopad")
pac("veracrypt")

fs.merge("files/terminator_config", "~/.config/terminator/config", mkdir=True)  # files
fs.merge("files/zshrc", "~/.zshrc")
fs.merge("files/profile", "~/.profile")
fs.merge("files/vimrc", "~/.vimrc")
fs.merge("files/gitconfig", "~/.gitconfig")
fs.merge("files/magnoster.zsh-theme", "~/.bin/magnoster.zsh-theme", mkdir=True)
fs.merge("files/pass", "~/.bin/pass", mkdir=True)
fs.merge("files/dockbash", "~/.bin/dockbash", mkdir=True)
fs.merge("files/unpushed", "~/.bin/unpushed", mkdir=True)
fs.merge("files/gradle.properties", "~/.gradle/gradle.properties", mkdir=True)
fs.symlink("~/.bin/magnoster.zsh-theme", "/usr/lib/prezto/modules/prompt/functions/prompt_magnoster_setup", sudo=True)
vera.merge_to_dir("~/shared/1", "~/.ssh/", force)                               # secrets

xfce.kb_set("/xfwm4/custom/<Control><Alt>Down", "hide_window_key", create=True) # wm stuff
xfce.kb_set("/xfwm4/custom/<Control><Alt>Left", "tile_left_key", create=True)
xfce.kb_set("/xfwm4/custom/<Control><Alt>Right", "tile_right_key", create=True)
xfce.kb_set("/xfwm4/custom/<Control><Alt>Up", "maximize_window_key", create=True)
xfce.kb_unset("/xfwm4/custom/<Alt>F6", "stick_window_key")                      # < messes up intellij
xfce.kb_unset("/xfwm4/custom/<Alt>F7", "move_window_key")                       # < messes up intellij
xfce.kb_unset("/xfwm4/custom/<Alt>Insert", "add_workspace_key")                 # < messes up intellij
xfce.wm_set("/general/mousewheel_rollup", "false")
xfce.wm_set("/general/scroll_workspaces", "false")
print("You might want to xfwm4 --replace if new shortcuts where set")

print("All good!")
